In [2]:
import numpy as np
import pandas as pd

In [15]:
df= pd.read_csv('data/nifty500_5yr_data.csv')
df.head()

,Date,Ticker,Open,High,Low,Close,Volume,Notes
0,2021-06-09,360ONE,260.813755,262.150806,249.887157,251.816010,59152.0,NaN
1,2021-06-10,360ONE,253.997012,260.046642,251.848943,257.131409,41084.0,NaN
2,2021-06-11,360ONE,259.443804,263.246739,256.714877,260.758942,232800.0,NaN
3,2021-06-14,360ONE,261.931602,263.027550,258.939658,259.619141,74364.0,NaN
4,2021-06-15,360ONE,260.791773,260.791773,252.144728,253.821533,149636.0,NaN

In [17]:
# df=df.iloc[:,:-1]
df

,Date,Ticker,Open,High,Low,Close,Volume
0,2021-06-09,360ONE,260.813755,262.150806,249.887157,251.816010,59152.0
1,2021-06-10,360ONE,253.997012,260.046642,251.848943,257.131409,41084.0
2,2021-06-11,360ONE,259.443804,263.246739,256.714877,260.758942,232800.0
3,2021-06-14,360ONE,261.931602,263.027550,258.939658,259.619141,74364.0
4,2021-06-15,360ONE,260.791773,260.791773,252.144728,253.821533,149636.0
...,...,...,...,...,...,...,...
551638,2026-06-03,ECLERX,1519.000000,1524.199951,1423.699951,1439.400024,436344.0
551639,2026-06-04,ECLERX,1431.699951,1432.000000,1403.000000,1407.599976,246205.0
551640,2026-06-05,ECLERX,1410.000000,1431.000000,1371.199951,1380.099976,186264.0
551641,2026-06-08,ECLERX,1375.000000,1408.000000,1341.199951,1384.800049,207300.0
551642,2026-06-09,ECLERX,1384.800049,1421.800049,1362.000000,1415.099976,241274.0

In [5]:
## Data sctructure
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 551643 entries, 0 to 551642
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Date    551643 non-null  str
 1   Ticker  551643 non-null  str
 2   Open    551643 non-null  float64
 3   High    551643 non-null  float64
 4   Low     551643 non-null  float64
 5   Close   551643 non-null  float64
 6   Volume  551643 non-null  float64
dtypes: float64(5), str(2)
memory usage: 29.5 MB

In [6]:
df.isnull().sum()

Date      0
Ticker    0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [7]:
import seaborn as sns
from matplotlib import pyplot as plt

In [8]:
df.corr(numeric_only=True)

            Open      High       Low     Close    Volume
Open    1.000000  0.999918  0.999937  0.999870 -0.052130
High    0.999918  1.000000  0.999900  0.999945 -0.052221
Low     0.999937  0.999900  1.000000  0.999936 -0.052011
Close   0.999870  0.999945  0.999936  1.000000 -0.052106
Volume -0.052130 -0.052221 -0.052011 -0.052106  1.000000

In [9]:
df.columns

Index(['Date', 'Ticker', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='str')

In [13]:
df.select_dtypes(include='O').columns

/var/folders/xn/v562jrt90ls80l0qp0wx71400000gn/T/ipykernel_62608/1932503071.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include='O').columns

Index(['Date', 'Ticker'], dtype='str')

In [12]:
df.select_dtypes(exclude='O').columns

Index(['Open', 'High', 'Low', 'Close', 'Volume'], dtype='str')

In [14]:
df.head(2)

         Date  Ticker        Open        High         Low       Close   Volume
0  2021-06-09  360ONE  260.813755  262.150806  249.887157  251.816010  59152.0
1  2021-06-10  360ONE  253.997012  260.046642  251.848943  257.131409  41084.0